"use strict";
exports.__esModule = true;
var message = "Welcome Back";
console.log(message);
var sum;
var title = "Kernelon";
var isBeginner = true;
var total = 0;
var name = "Vinod";
var sentance = "My name is " + name + " \nI am a beginner in TypeScript";
console.log(sentance);
var list1 = [1, 2, 3, 4, 5];
var list2 = [1, 2, 3, 4, 5];
console.log(list1, list2);
var person1 = ['Chris', 22];
var person2 = [32, 'Leo'];
console.log(person1, person2);
var color;
(function (color) {
    color[color["Red"] = 0] = "Red";
    color[color["Blue"] = 1] = "Blue";
    color[color["Green"] = 2] = "Green";
})(color || (color = {}));
;
var r = color.Red;
var b = color.Blue;
var g = color.Green;
console.log(g, b, r);
